# Import config file
configfile: "config/config.yaml"

# Modules
if config["input_files"]["data"]["type"] == "ONT":
    include: "rules/install_dorado.smk"
    include: "rules/dorado.smk"
if config["input_files"]["data"]["type"] == "PacBio":
    include: "rules/fibertools_predict.smk"
include: "rules/bam_to_fastq_gz.smk"
include: "rules/quality_control.smk"
include: "rules/install_kraken2_db.smk"
include: "rules/kraken2.smk"
include: "rules/minimap2.smk"
include: "rules/modkit.smk"

outputs = [
    config["results"]["bam_dir"],
    config["results"]["fastq_gz_dir"],
    config["results"]["kraken2"]["dir"],
    config["results"]["kraken2"]["kraken2_mpa_path"],
    config["results"]["qc"]["sequali"]["dir"],
    config["results"]["qc"]["multi_qc_report_path"],
    config["results"]["minimap2"]["filtered_dir"],
    config["results"]["modkit"]["dir"]
]

if config["tabix"]:
    outputs.append(config["results"]["tabix"]["dir"])
    include: "rules/tabix.smk"

rule all:
    input:
        outputs
